name: Deploy to DEV
on:
  push:
    branches:
      - develop
  workflow_dispatch: # Manual github trigger (by pressing "Run workflow" on Github "Actions" tab)

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run test suite (includes pip install)
#         run: openfisca test openfisca_nsw_safeguard/tests/ --country-package openfisca_nsw_base --extensions openfisca_nsw_safeguard

  deploy:
#     needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_VM_HOST }}
          username: ${{ secrets.DEV_VM_USER }}
          key: ${{ secrets.DEV_VM_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            source venv/bin/activate
            cd openfisca_nsw_safeguard
            git fetch --all
            git reset --hard origin/develop
            pip install --editable .[dev] --upgrade
            sudo supervisorctl stop all
            /home/$username/venv/bin/openfisca serve --workers=3 --country-package openfisca_nsw_base --extensions openfisca_nsw_safeguard --bind 0.0.0.0:8000
            exit

  trigger-djangoapi-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch # Sends webhook to `openfisca-djangoapi` repo which triggers deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DJANGO_API }}
          repository: energy-savings-scheme/openfisca-djangoapi
          event-type: dev-openfisca-ruleset-updated
