name: Deploy to DEV
on:
  push:
    branches:
      - develop
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
  pull_request:
  workflow_dispatch: # Manual github trigger (by pressing "Run workflow" on Github "Actions" tab)

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Setup Python
        run: |
          uv python install 3.8 && \
          uv venv --python=3.8 && \
          uv pip install --editable .[dev] --upgrade && \
          uv pip install --upgrade Jinja2==3.0.1 itsdangerous==2.0.1 pytest
      - name: Run test suite
        run: |
          export PYTHONPATH="$(pwd):$PYTHONPATH"
          source .venv/bin/activate
          openfisca test openfisca_nsw_safeguard/tests/ --country-package openfisca_nsw_base --extensions openfisca_nsw_safeguard

  deploy:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_VM_HOST }}
          username: ${{ secrets.DEV_VM_USER }}
          key: ${{ secrets.DEV_VM_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            source venv/bin/activate
            cd openfisca_nsw_safeguard
            git fetch --all
            git reset --hard origin/develop
            pip install --editable .[dev] --upgrade
            sudo supervisorctl restart all
            exit

  trigger-djangoapi-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch # Sends webhook to `openfisca-djangoapi` repo which triggers deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DJANGO_API }}
          repository: energy-savings-scheme/openfisca-djangoapi
          event-type: dev-openfisca-ruleset-updated
