name: Deploy to PROD
on:
  push:
    branches:
      - master
  pull_request: {}
  # Manual github trigger (by pressing "Run workflow" on Github "Actions" tab)
  workflow_dispatch:
# Ensure previous run with the same workflow/PR/branch will be cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Setup Python
        run: |
          uv python install 3.8 && \
          uv venv --python=3.8 && \
          uv pip install --editable .[dev] --upgrade && \
          uv pip install --upgrade Jinja2==3.0.1 itsdangerous==2.0.1 pytest
      - name: Run test suite
        run: |
          export PYTHONPATH="$(pwd):$PYTHONPATH"
          source .venv/bin/activate
          openfisca test openfisca_nsw_safeguard/tests/ --country-package openfisca_nsw_base --extensions openfisca_nsw_safeguard

  deploy:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    # Ensure just run when there is changes in the branch
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRD_VM_HOST }}
          username: ${{ secrets.PRD_VM_USER }}
          key: ${{ secrets.PRD_VM_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            source venv/bin/activate
            cd openfisca_nsw_safeguard
            git fetch --all
            git reset --hard origin/master
            pip install --editable .[dev] --upgrade
            sudo supervisorctl restart all
            exit

  trigger-djangoapi-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch # Sends webhook to `openfisca-djangoapi` repo which triggers deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DJANGO_API }}
          repository: energy-savings-scheme/openfisca-djangoapi
          event-type: prod-openfisca-ruleset-updated
